# Generated by Django 5.0.3 on 2024-05-31 16:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('service', models.CharField(choices=[('WH', 'Web Hosting'), ('WD', 'Web Design'), ('DM', 'Digital Marketing'), ('OT', 'Other')], max_length=2)),
                ('message', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
