# Generated by Django 5.0.3 on 2024-06-06 18:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_hero'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('highlight_text', models.TextField()),
                ('year', models.IntegerField()),
                ('mission_text', models.TextField()),
                ('vision_text', models.TextField()),
                ('values_text', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
