# Generated by Django 5.0.3 on 2024-11-07 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit', models.PositiveIntegerField()),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
